server:
	port: 8080
  servlet:
		context-path: /api
		
# Data base Connection
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ytech
    username: postgres
    password: vicente0301
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
		show-sql: true
		generate-ddl: true
		hibernate:
			ddl-auto: update
		properties:
			hibernate:
				jdbc:
					lob:
						non_contextual_creation: true
  main:
		allow-circular-references: true
		
# Swegger
	mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

# Spring Security and token JWT
security:
	jwt:
		expiracao: 30
		chave-assinatura: 764811743f33067f36d72dd04ce22a27
	password:
		reset: http://localhost:8080/api/user/password/reset?token=
			
		